{
    trafficRegistrationPoints {
        id
        name
        latestData {
            volumeByHour
        }
        location {
            coordinates {
                latLon {
                    lat
                    lon
                }
            }
        }
    }
}


vol_qry = function(id, from, to) 
  {
  query = paste0("SELECT * FROM VOLUME_DATA WHERE ID = '", id, 
                  "' AND DATE_TIME BETWEEN '", from, 
                  "' AND '", to, "';")
  return(query)
}